/** Filas BullMQ independentes. Os valores são os nomes reais das filas no Redis. */
export const QUEUE_NAMES = {
  AI_GENERATION: 'AI_GENERATION',
  CONTENT_PROCESSING: 'CONTENT_PROCESSING',
  CONTENT_PUBLICATION: 'CONTENT_PUBLICATION',
  CONTENT_SCHEDULING: 'CONTENT_SCHEDULING',
  ANALYTICS_COLLECTION: 'ANALYTICS_COLLECTION',
  AI_HEALTH_CHECK: 'AI_HEALTH_CHECK',
  NOTIFICATIONS: 'NOTIFICATIONS',
  SEO_ANALYSIS: 'SEO_ANALYSIS',
  WEBHOOK_PROCESSING: 'WEBHOOK_PROCESSING',
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];
